sudo: required

language: generic

services:
  - docker

env:
  global:
    - COMPOSE_FILE=docker-compose.ci.yml
    - COMPOSE_PROJECT_NAME=identidock${TRAVIS_BRANCH}

script:
  - ./build.sh

after_script:
  - docker-compose down