sudo: required

language: python

python:
  - "3.6"

services:
  - docker

env:
  - COMPOSE_FILE=docker-compose.ci.yml
  - COMPOSE_PROJECT_NAME=identidock${TRAVIS_BRANCH}

before_script:
  - docker -v
  - docker-compose -v
  - docker-compose ps

script:
  - docker-compose build --no-cache

after_script:
  - docker-compose down