version: '{build}-{branch}'
image: Visual Studio 2017 # supports docker

environment:
    COMPOSE_FILE: docker-compose.ci.yml
    COMPOSE_PROJECT_NAME: identidock{branch}

install:
  - docker version
  - choco install -y docker-compose
  - choco install -y python

before_build:
  - docker-compose down

build_script:
  - docker-compose build --no-cache

before_test:
  - docker-compose up -d

test_script:
  # Run unit tests
  - docker-compose run --no-deps --rm -e ENV=UNIT identidock

after_test:
  - docker-compose down
